<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>steadypath_ros2</name>
  <version>1.0.0</version>
  <description>SteadyPath Autonomous Guided Vehicle (AGV) High-Precision Motion Control, Constrained MPC, Dynamic Replanning and Telemetry Logging Package.</description>
  <maintainer email="basappababanagar911@example.com">Basappa Babanagar</maintainer>
  <author email="basappababanagar911@example.com">SteadyPath AGV Core Team</author>
  <license>Apache-2.0</license>

  <!-- Build Tool Dependencies -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Runtime ROS 2 Dependencies -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <!-- Test Dependencies -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
